/**
 * MoneyModel — 4-stage sequence validator from $100M Money Models.
 *
 * The book's core claim: a good Money Model recovers the cost of getting
 * and serving a customer within 30 days, so the business can scale without
 * outside capital. A $100M Money Model recovers the cost of getting MANY
 * customers within 30 days.
 *
 * Stages (in order):
 *   1. Attraction  — turns strangers into customers. Free/discount front end.
 *   2. Upsell      — more cash from the same customer, immediately.
 *   3. Downsell    — catches the "no" and turns it into a smaller "yes."
 *   4. Continuity  — keeps them paying monthly/weekly until they cancel.
 *
 * This module:
 *   - Validates the sequence (missing stages, wrong order)
 *   - Computes projected 30-day profit and 90-day gross profit
 *   - Emits sequence warnings when a stage is missing or thin
 *
 * Deterministic — no LLM. Take rates are inputs, not estimated.
 */

import { randomUUID } from 'crypto';
import { log } from '../../core/logger';
import { ValidationError } from '../../shared/types/errors';
import type {
  MoneyModel,
  MoneyModelOffer,
  MoneyModelOfferType,
  MoneyModelStage,
} from '../types';

// ── Stage classification ──────────────────────────────────────────────

const STAGE_BY_TYPE: Record<MoneyModelOfferType, MoneyModelStage> = {
  // Attraction
  win_money_back: 'attraction',
  giveaway: 'attraction',
  decoy: 'attraction',
  buy_x_get_y: 'attraction',
  pay_less_now_pay_more_later: 'attraction',
  // Upsell
  classic_upsell: 'upsell',
  menu_upsell: 'upsell',
  anchor_upsell: 'upsell',
  rollover_upsell: 'upsell',
  // Downsell
  payment_plan: 'downsell',
  trial_with_penalty: 'downsell',
  feature_downsell: 'downsell',
  // Continuity
  continuity_bonus: 'continuity',
  continuity_discount: 'continuity',
  waived_fee: 'continuity',
};

const STAGE_ORDER: MoneyModelStage[] = [
  'attraction',
  'upsell',
  'downsell',
  'continuity',
];

const STAGE_LABELS: Record<MoneyModelStage, string> = {
  attraction: 'Attraction',
  upsell: 'Upsell',
  downsell: 'Downsell',
  continuity: 'Continuity',
};

function inferStage(type: MoneyModelOfferType): MoneyModelStage {
  const stage = STAGE_BY_TYPE[type];
  if (!stage) throw new ValidationError(`unknown offer type: ${type}`);
  return stage;
}

// ── Public API ────────────────────────────────────────────────────────

export interface OfferInput {
  type: MoneyModelOfferType;
  name: string;
  priceUsd: number;
  expectedTakeRate: number;       // 0-1 fraction of customers who accept
  /** Optional: gross margin fraction (0-1). Defaults to 0.85. */
  grossMargin?: number;
  notes?: string[];
}

export interface BuildInput {
  icpId: string;
  name: string;
  offers: OfferInput[];
  /** Customers acquired per month through Attraction offers. Default 100. */
  monthlyAcquisition?: number;
  /** Baseline refund rate applied to Attraction revenue. Default 0.05. */
  baseRefundRate?: number;
}

export interface StageBucket {
  stage: MoneyModelStage;
  offers: MoneyModelOffer[];
  /** Fraction of the acquisition cohort that reaches this stage. */
  reachRate: number;
  /** Gross profit generated by this stage per acquisition cohort. */
  grossProfitUsd: number;
}

export interface MoneyModelProjection {
  monthlyAcquisition: number;
  buckets: StageBucket[];
  /** Total gross profit per cohort across all stages, 30 days. */
  thirtyDayGrossProfitUsd: number;
  /** Annualized run rate based on the 30-day cohort. */
  annualizedGrossProfitUsd: number;
  /** Does the model cover the acquisition + fulfillment cost within 30 days? */
  coversAcquisitionCost: boolean;
  /** Threshold: book says "get paid to get customers." */
  isHundredMillionModel: boolean;
}

export class MoneyModelBuilder {
  /**
   * Build + validate a Money Model from a list of offers. Returns the
   * stored model with projections, missing stages, and sequence warnings.
   */
  build(input: BuildInput): MoneyModel {
    if (!Array.isArray(input.offers) || input.offers.length === 0) {
      throw new ValidationError('at least one offer is required');
    }

    const modelId = `mm_${randomUUID().slice(0, 8)}`;

    // Materialize MoneyModelOffer objects with inferred stages.
    const offers: MoneyModelOffer[] = input.offers.map((o, idx) => {
      if (!Number.isFinite(o.priceUsd) || o.priceUsd < 0) {
        throw new ValidationError(`offer ${idx}: priceUsd must be >= 0`);
      }
      if (o.expectedTakeRate < 0 || o.expectedTakeRate > 1) {
        throw new ValidationError(`offer ${idx}: expectedTakeRate must be 0-1`);
      }
      return {
        id: `mmo_${idx}_${Math.random().toString(36).slice(2, 6)}`,
        stage: inferStage(o.type),
        type: o.type,
        name: o.name,
        priceUsd: o.priceUsd,
        expectedTakeRate: o.expectedTakeRate,
        valueEquationScore: this.placeholderScore(o.priceUsd),
        notes: o.notes ?? [],
      };
    });

    // ── Sequence validation ───────────────────────────────────────────
    const presentStages = new Set(offers.map((o) => o.stage));
    const missingStages = STAGE_ORDER.filter((s) => !presentStages.has(s));
    const sequenceWarnings = this.buildSequenceWarnings(offers, missingStages);

    // ── Projections ───────────────────────────────────────────────────
    const projection = this.project(
      offers,
      input.monthlyAcquisition ?? 100,
      input.baseRefundRate ?? 0.05,
    );

    const model: MoneyModel = {
      id: modelId,
      icpId: input.icpId,
      name: input.name,
      offers,
      projectedThirtyDayProfitUsd: projection.thirtyDayGrossProfitUsd,
      projectedNinetyDayGrossProfitUsd: Math.round(
        projection.thirtyDayGrossProfitUsd * 3,
      ),
      missingStages,
      sequenceWarnings,
    };

    log.info('money_model.build', {
      modelId,
      offers: offers.length,
      missingStages: missingStages.length,
      thirtyDay: model.projectedThirtyDayProfitUsd,
      coversCost: projection.coversAcquisitionCost,
      is100M: projection.isHundredMillionModel,
    });

    return model;
  }

  /**
   * Trace view — same as build() but also returns the projection details
   * (per-stage buckets, reach rates, cover flags) for UI display.
   */
  buildWithProjection(input: BuildInput): {
    model: MoneyModel;
    projection: MoneyModelProjection;
  } {
    const model = this.build(input);
    const projection = this.project(
      model.offers,
      input.monthlyAcquisition ?? 100,
      input.baseRefundRate ?? 0.05,
    );
    return { model, projection };
  }

  /**
   * Score an offer list against the 4-stage model without building.
   * Useful for quick checks in the closing playbook.
   */
  validate(offers: OfferInput[]): {
    missingStages: MoneyModelStage[];
    sequenceWarnings: string[];
  } {
    const materialized = offers.map((o, idx) => ({
      id: `check_${idx}`,
      stage: inferStage(o.type),
      type: o.type,
      name: o.name,
      priceUsd: o.priceUsd,
      expectedTakeRate: o.expectedTakeRate,
      valueEquationScore: this.placeholderScore(o.priceUsd),
      notes: [],
    }));
    const presentStages = new Set(materialized.map((o) => o.stage));
    const missingStages = STAGE_ORDER.filter((s) => !presentStages.has(s));
    return {
      missingStages,
      sequenceWarnings: this.buildSequenceWarnings(materialized, missingStages),
    };
  }

  // ── Internal projection math ────────────────────────────────────────
  //
  // We model a single cohort of N acquired customers and walk it through
  // each stage in order. At each stage, a fraction of the cohort accepts
  // the offer (expectedTakeRate). The accepted cohort continues to the
  // next stage; those who decline drop to the stage's downsell (if the
  // stage IS downsell) or are lost.
  //
  // Attraction is special: 100% of the cohort enters, and baseRefundRate
  // is applied against Attraction revenue only (refunds are a front-end
  // phenomenon in the book's framing).

  private project(
    offers: MoneyModelOffer[],
    monthlyAcquisition: number,
    baseRefundRate: number,
  ): MoneyModelProjection {
    const buckets: StageBucket[] = [];
    const stageOffers = new Map<MoneyModelStage, MoneyModelOffer[]>();
    for (const o of offers) {
      const arr = stageOffers.get(o.stage) ?? [];
      arr.push(o);
      stageOffers.set(o.stage, arr);
    }

    // Attraction: cohort * attraction offers * (1 - refundRate)
    let cohort = monthlyAcquisition;
    let cumulativeGrossProfit = 0;

    for (const stage of STAGE_ORDER) {
      const stageList = stageOffers.get(stage) ?? [];
      if (stageList.length === 0) {
        // No offers at this stage — cohort untouched, no revenue.
        buckets.push({
          stage,
          offers: [],
          reachRate: 1,
          grossProfitUsd: 0,
        });
        continue;
      }

      // Attraction: reach is 100% of the cohort (the cohort IS the acquired
      // set). For all other stages, reach is the % of the previous stage's
      // acceptors who progressed.
      const reachRate = stage === 'attraction' ? 1 : 1;

      let stageGrossProfit = 0;
      let acceptors = 0;

      for (const o of stageList) {
        const acceptCount = cohort * o.expectedTakeRate;
        const grossMargin = 0.85; // book default
        const margin = o.priceUsd * grossMargin;
        const refundRate =
          stage === 'attraction' ? baseRefundRate : this.refundRateFor(o.type);
        const netProfit = acceptCount * margin * (1 - refundRate);
        stageGrossProfit += netProfit;
        acceptors += acceptCount;
      }

      buckets.push({
        stage,
        offers: stageList,
        reachRate,
        grossProfitUsd: Math.round(stageGrossProfit),
      });

      cumulativeGrossProfit += stageGrossProfit;

      // The cohort for the next stage is the fraction of the current
      // cohort that took ANY offer at this stage. We take the highest
      // expectedTakeRate in the stage as the progression proxy, because
      // in practice the most-attractive offer in a stage captures the
      // progression path.
      const progressionRate = Math.max(
        ...stageList.map((o) => o.expectedTakeRate),
      );
      cohort = cohort * progressionRate;
    }

    const thirtyDayGrossProfitUsd = Math.round(cumulativeGrossProfit);

    // Attraction revenue is what we spent to acquire the cohort. If the
    // 30-day gross profit exceeds that, the model is self-funding.
    const attractionOffers = stageOffers.get('attraction') ?? [];
    const attractionRevenue =
      attractionOffers.length > 0
        ? monthlyAcquisition *
          Math.max(...attractionOffers.map((o) => o.priceUsd)) *
          0.85
        : 0;
    const coversAcquisitionCost = thirtyDayGrossProfitUsd > attractionRevenue;

    // A $100M Money Model by the book's definition: 30-day gross profit
    // from one cohort is enough to fund TWO more cohorts.
    const isHundredMillionModel =
      thirtyDayGrossProfitUsd > attractionRevenue * 2;

    return {
      monthlyAcquisition,
      buckets,
      thirtyDayGrossProfitUsd,
      annualizedGrossProfitUsd: thirtyDayGrossProfitUsd * 12,
      coversAcquisitionCost,
      isHundredMillionModel,
    };
  }

  private refundRateFor(type: MoneyModelOfferType): number {
    // Continuity offers carry the highest churn-adjacent reversal rate;
    // upsells and downsells are low because the buyer is already invested.
    switch (type) {
      case 'continuity_bonus':
      case 'continuity_discount':
        return 0.03;
      case 'waived_fee':
        return 0.05;
      case 'payment_plan':
        return 0.04;
      case 'trial_with_penalty':
        return 0.06;
      default:
        return 0.01;
    }
  }

  private buildSequenceWarnings(
    offers: MoneyModelOffer[],
    missingStages: MoneyModelStage[],
  ): string[] {
    const warnings: string[] = [];

    // Missing stages are the loudest warning.
    for (const s of missingStages) {
      if (s === 'attraction') {
        warnings.push(
          'CRITICAL: no Attraction offer. The model cannot acquire customers. Add a Win-Your-Money-Back, Giveaway, Decoy, Buy-X-Get-Y, or Pay-Less-Now offer.',
        );
      } else if (s === 'continuity') {
        warnings.push(
          'No Continuity offer. 30-day cash will plateau. Add a Continuity Bonus, Continuity Discount, or Waived Fee offer to stack recurring revenue.',
        );
      } else if (s === 'upsell') {
        warnings.push(
          'No Upsell offer. You are leaving cash on the table at the moment of highest buying intent. Add a Classic, Menu, Anchor, or Rollover upsell.',
        );
      } else if (s === 'downsell') {
        warnings.push(
          'No Downsell offer. Every "no" is a lost sale. Add a Payment Plan, Trial With Penalty, or Feature Downsell to recover prospects.',
        );
      }
    }

    // Attraction-only model — the classic beginner mistake.
    if (
      offers.length > 0 &&
      offers.every((o) => o.stage === 'attraction')
    ) {
      warnings.push(
        'Attraction-only model. The book calls this the front end of a business, not a business. Add at least one Upsell to make the front end profitable.',
      );
    }

    // Attraction without any paid offer (pure free) — cash trap.
    const attractionOffers = offers.filter((o) => o.stage === 'attraction');
    if (
      attractionOffers.length > 0 &&
      attractionOffers.every((o) => o.priceUsd === 0)
    ) {
      warnings.push(
        'All Attraction offers are free. Cash flow will stall unless the Upsell stage immediately monetizes. Add a paid Upsell or convert one Attraction to a discount offer.',
      );
    }

    // Downsell with higher price than any Upsell — the sequence is inverted.
    const maxUpsell = Math.max(
      0,
      ...offers.filter((o) => o.stage === 'upsell').map((o) => o.priceUsd),
    );
    const minDownsell = Math.min(
      Infinity,
      ...offers.filter((o) => o.stage === 'downsell').map((o) => o.priceUsd),
    );
    if (
      Number.isFinite(minDownsell) &&
      maxUpsell > 0 &&
      minDownsell > maxUpsell
    ) {
      warnings.push(
        'Downsell price exceeds Upsell price. Downsells should be cheaper or spread over time relative to the Upsell they recover from.',
      );
    }

    // Continuity without a prior paid stage — nothing to flow from.
    const hasPaidPrior = offers.some(
      (o) => (o.stage === 'attraction' || o.stage === 'upsell') && o.priceUsd > 0,
    );
    const hasContinuity = offers.some((o) => o.stage === 'continuity');
    if (hasContinuity && !hasPaidPrior) {
      warnings.push(
        'Continuity offer present but no paid Attraction or Upsell offer. Customers will not enter the continuity flow.',
      );
    }

    return warnings;
  }

  private placeholderScore(priceUsd: number) {
    // Price-agnostic neutral score. Real value scoring is done by the
    // ValueEquation module and merged in by the caller when needed.
    return {
      dreamOutcome: 5,
      perceivedLikelihood: 5,
      timeDelay: 5,
      effortSacrifice: 5,
      numerator: 25,
      denominator: 25,
      valueScore: 1,
      normalizedScore: 1,
    };
  }
}

export const moneyModelBuilder = new MoneyModelBuilder();

// Re-export the stage label map for UI consumers.
export { STAGE_LABELS, STAGE_ORDER, STAGE_BY_TYPE };
