import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File, Paths } from 'expo-file-system';
import type { ScanRecord, FeatureRecord } from '@/db/schema';

function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 * 1024 * 1024) return `${(n / 1024 / 1024).toFixed(1)} MB`;
  return `${(n / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

function fmtDate(ms: number): string {
  return new Date(ms).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
}

function escape(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c] as string));
}

export function scanToMarkdown(
  scan: ScanRecord,
  features: FeatureRecord[],
): string {
  const lines: string[] = [];
  lines.push(`# ModKit Scan Report`);
  lines.push('');
  lines.push(`**APK:** \`${scan.apkName}\``);
  lines.push(`**Path:** \`${scan.apkPath}\``);
  lines.push(`**Size:** ${fmtBytes(scan.apkSize)}`);
  lines.push(`**Fingerprint (SHA256):** \`${scan.apkHash}\``);
  lines.push(`**Scanned:** ${fmtDate(scan.scannedAt)}`);
  lines.push(`**Duration:** ${(scan.elapsedMs / 1000).toFixed(2)}s`);
  lines.push('');
  lines.push(`## Archive`);
  lines.push(`- DEX files: ${scan.dexParsed} / ${scan.dexTotal}`);
  lines.push(`- Classes parsed: ${scan.totalClasses}`);
  lines.push(`- Features scanned: ${scan.featureCount}`);
  lines.push(`- Features with hits: ${scan.hitFeatureCount}`);
  lines.push('');
  lines.push(`## Findings`);
  const sorted = [...features].sort((a, b) => b.totalHits - a.totalHits);
  for (const f of sorted) {
    const patterns: string[] = JSON.parse(f.patterns || '[]');
    lines.push('');
    lines.push(`### ${f.featureId} — ${f.status.toUpperCase()}`);
    lines.push(`- ${f.message}`);
    if (f.totalHits > 0) {
      lines.push(`- Total hits: ${f.totalHits} DEX files (${f.dexCount} distinct)`);
    }
    if (f.topSignalClass) {
      lines.push(`- Top signal class: \`${f.topSignalClass}\``);
    }
    if (patterns.length > 0) {
      lines.push(`- Patterns matched: ${patterns.map((p) => `\`${p}\``).join(', ')}`);
    }
  }
  if (scan.patchPlan) {
    lines.push('');
    lines.push(`## Patch Plan (${scan.reportGoal ?? 'unknown'})`);
    try {
      const plan = JSON.parse(scan.patchPlan);
      if (plan.summary) {
        lines.push('');
        lines.push(plan.summary);
      }
      if (plan.findings) {
        lines.push('');
        lines.push('### Findings');
        for (const fd of plan.findings) {
          lines.push(`- **${fd.id}** [${fd.risk}] → ${fd.target}`);
          lines.push(`  - evidence: ${fd.evidence}`);
          lines.push(`  - defeat: ${fd.defeat}`);
        }
      }
      if (plan.patchPlan) {
        lines.push('');
        lines.push('### Steps');
        for (const st of plan.patchPlan) {
          lines.push(`${st.step}. **${st.action.toUpperCase()}** \`${st.file}\``);
          lines.push(`   - ${st.rationale}`);
        }
      }
    } catch {
      lines.push('(patch plan could not be parsed)');
    }
  }
  lines.push('');
  lines.push('---');
  lines.push(`Generated by ModKit · ${fmtDate(Date.now())}`);
  return lines.join('\n');
}

export function scanToHtml(
  scan: ScanRecord,
  features: FeatureRecord[],
): string {
  const md = scanToMarkdown(scan, features);
  const esc = escape(md);
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>ModKit Report</title>
<style>
  body { font: 13px/1.55 -apple-system,Menlo,monospace; color:#111; background:#fff; padding:32px; max-width:820px; margin:0 auto; }
  pre { white-space:pre-wrap; word-break:break-word; }
  h1 { color:#0a0; border-bottom:2px solid #0a0; padding-bottom:6px; }
  code { background:#f4f4f4; padding:1px 4px; border-radius:3px; font-family:Menlo,monospace; }
  hr { border:0; border-top:1px solid #ddd; margin:22px 0; }
</style></head>
<body><pre>${esc}</pre></body></html>`;
}

export async function shareScanMarkdown(
  scan: ScanRecord,
  features: FeatureRecord[],
): Promise<void> {
  const md = scanToMarkdown(scan, features);
  const safeName = scan.apkName.replace(/[^a-zA-Z0-9_.-]/g, '_');
  const file = new File(Paths.cache, `modkit-${safeName}-${scan.id}.md`);
  if (file.exists) file.delete();
  file.create();
  file.write(md);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(file.uri, {
      mimeType: 'text/markdown',
      dialogTitle: `ModKit report — ${scan.apkName}`,
      UTI: 'net.daringfireball.markdown',
    });
  }
}

export async function shareScanPdf(
  scan: ScanRecord,
  features: FeatureRecord[],
): Promise<void> {
  const html = scanToHtml(scan, features);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `ModKit report — ${scan.apkName}`,
      UTI: 'com.adobe.pdf',
    });
  }
}
