export interface SovereignEvent<T = unknown> {
  event_type: string;
  source: string;
  payload: T;
  correlation_id?: string;
  timestamp: number;
}

export type EventHandler<T = unknown> = (event: SovereignEvent<T>) => Promise<void> | void;

export const EVENTS = {
  CHAT_COMMAND_PARSED: 'CHAT.COMMAND_PARSED',
  CHAT_REPLY_READY: 'CHAT.REPLY_READY',
  TERMUX_EXECUTE_COMMAND: 'TERMUX.EXECUTE_COMMAND',
  TERMUX_COMMAND_RESULT: 'TERMUX.COMMAND_RESULT',
  GODMODE_LATENCY_STORM: 'GODMODE.LATENCY_STORM',
  GODMODE_REPORT: 'GODMODE.REPORT',
  MYSTIC_MANIFEST: 'MYSTIC.MANIFEST',
  MYSTIC_SPEC_READY: 'MYSTIC.SPEC_READY',
  WORKSPACE_CREATE_FILE: 'WORKSPACE.CREATE_FILE',
  WORKSPACE_FILE_UPDATED: 'WORKSPACE.FILE_UPDATED',
  WORKSPACE_BUILD_SUCCEEDED: 'WORKSPACE.BUILD_SUCCEEDED',
  WORKSPACE_BUILD_FAILED: 'WORKSPACE.BUILD_FAILED',
  WORKSPACE_LIST_DIR: 'WORKSPACE.LIST_DIR',
  WORKSPACE_FILE_READ: 'WORKSPACE.FILE_READ',
  WORKSPACE_WRITE_FILE: 'WORKSPACE.WRITE_FILE',
  WORKSPACE_RESULT: 'WORKSPACE.RESULT',
  POWERLAYER_METRICS_PUSH: 'POWERLAYER.METRICS_PUSH',
  POWERLAYER_ALERT: 'POWERLAYER.ALERT',
  POWERLAYER_STATE_SNAPSHOT: 'POWERLAYER.STATE_SNAPSHOT',
  SOVEREIGN_MISSION_DEFINE: 'SOVEREIGN.MISSION_DEFINE',
  SOVEREIGN_MISSION_EXECUTE: 'SOVEREIGN.MISSION_EXECUTE',
} as const;

export type EventName = typeof EVENTS[keyof typeof EVENTS];
