import type { Feature } from '@/types';

export const features: Feature[] = [
  {
    id: 'aimbot',
    index: 1,
    name: 'Target Lock',
    shortName: 'Target',
    description: 'Auto-lock the viewport onto tracked entities with adjustable field-of-view and smoothing. Silent tracking resolves without altering the target.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Fingerprint',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'wall-vision',
    index: 2,
    name: 'Wall Vision',
    shortName: 'Vision',
    description: 'Overlay tracked entity positions, state, distance, and loot through occluding geometry. Box, skeleton, and line render modes.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Eye',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'speed-sandbox',
    index: 3,
    name: 'Speed Sandbox',
    shortName: 'Speed',
    description: 'Scale subject movement speed while staying under observer thresholds. Sprint, walk, and prone modifiers.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Zap',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'recoil-control',
    index: 4,
    name: 'Recoil Control',
    shortName: 'Recoil',
    description: 'Neutralize vertical and horizontal recoil patterns across all weapons. Per-weapon tuning profiles.',
    category: 'behavior',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'TrendingDown',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'magic-bullet',
    index: 5,
    name: 'Projectile Redirect',
    shortName: 'Redirect',
    description: 'Redirect projectiles to the nearest tracked target. Alters hit registration.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Sparkles',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'no-recoil',
    index: 6,
    name: 'Recoil Elimination',
    shortName: 'NoRecoil',
    description: 'Zero recoil on all weapons. The reticle stays centered during sustained fire.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Activity',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'instant-hit',
    index: 7,
    name: 'Hitscan Conversion',
    shortName: 'Hitscan',
    description: 'Projectiles register on the same frame as the shot, with no travel time.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Zap',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'auto-headshot',
    index: 8,
    name: 'Critical Lock',
    shortName: 'CritLock',
    description: 'Force every shot to register as a critical hit. Bypasses hitbox validation on the observer.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Fingerprint',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'radar-sandbox',
    index: 9,
    name: 'Radar Sandbox',
    shortName: 'Radar',
    description: 'Full-map awareness — stream all subjects, vehicles, and loot to the minimap in real time.',
    category: 'intelligence',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Network',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'item-esp',
    index: 10,
    name: 'Loot Vision',
    shortName: 'LootVision',
    description: 'Highlight high-value loot through geometry with distance and name labels.',
    category: 'intelligence',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Box',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'vehicle-esp',
    index: 11,
    name: 'Vehicle Vision',
    shortName: 'VehVision',
    description: 'Reveal all vehicles with fuel, integrity, and distance through terrain.',
    category: 'intelligence',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'Share2',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'grenade-helper',
    index: 12,
    name: 'Trajectory Helper',
    shortName: 'Trajectory',
    description: 'Trajectory prediction for thrown objects with bounce simulation and a landing marker.',
    category: 'behavior',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'Share',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'anti-recoil-pro',
    index: 13,
    name: 'Recoil Compensation',
    shortName: 'Compensation',
    description: 'Advanced recoil compensation with weapon-specific patterns and burst control.',
    category: 'behavior',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Gauge',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'fast-loot',
    index: 14,
    name: 'Instant Pickup',
    shortName: 'Pickup',
    description: 'Items are collected the moment the reticle meets them.',
    category: 'behavior',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Download',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'no-reload',
    index: 15,
    name: 'Infinite Ammo',
    shortName: 'Ammo',
    description: 'No reload cycle — the magazine never depletes.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'RefreshCw',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'wall-shoot',
    index: 16,
    name: 'Wall Penetration',
    shortName: 'Penetration',
    description: 'Projectiles penetrate all surfaces — buildings, terrain, and vehicles.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'ShieldHalf',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'teleport',
    index: 17,
    name: 'Teleport',
    shortName: 'Teleport',
    description: 'Instant repositioning to any map coordinate. Bypasses movement validation.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Globe',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'flight-sandbox',
    index: 18,
    name: 'Flight Sandbox',
    shortName: 'Flight',
    description: 'Vertical movement — ascend, descend, and hover with no fall damage.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Cloud',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'invisible',
    index: 19,
    name: 'Cloaking',
    shortName: 'Cloak',
    description: 'Subject cloaking — observers cannot see or target you.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'EyeOff',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'god-mode',
    index: 20,
    name: 'Invincibility',
    shortName: 'Invincible',
    description: 'Zero damage from all sources — health never depletes.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'ShieldCheck',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'unlock-all',
    index: 21,
    name: 'Asset Unlock',
    shortName: 'Unlock',
    description: 'Unlock all skins, outfits, weapon finishes, and pass rewards locally.',
    category: 'accounts',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'KeyRound',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'rank-spoof',
    index: 22,
    name: 'Rank Spoof',
    shortName: 'RankSpoof',
    description: 'Display any rank and tier in lobbies. Visual only — no observer-side change.',
    category: 'accounts',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'Layers',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'anti-ban',
    index: 23,
    name: 'Anti-Detection Shield',
    shortName: 'AntiDetect',
    description: 'Signature randomization, memory cloaking, and behavioral mimicry to evade detection.',
    category: 'forensics',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Lock',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
];

export function getFeatureById(id: string): Feature | undefined {
  return features.find((f) => f.id === id);
}
