import type { Feature } from '@/types';

export const features: Feature[] = [
  { id: 'policy-orchestration', index: 24, name: 'Policy & Orchestration Layer', shortName: 'Policy', category: 'policy', description: 'Central config for all security and update rules. Signed, versioned JSON/YAML policy bundles controlling which layers are active per environment.', icon: 'Settings2', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'device-fingerprint', index: 25, name: 'Identity & Device Fingerprint Layer', shortName: 'DevID', category: 'identity', description: 'Builds a soft device fingerprint from multiple signals (OS, model, timezone, locale, install age). Returns a rotating, non-PII Device Stealth ID with weighted confidence score.', icon: 'Fingerprint', status: 'active', riskLevel: 'low', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'session-integrity', index: 26, name: 'Session & Context Integrity Layer', shortName: 'Session', category: 'integrity', description: 'Tracks session tokens, login context, and environment. Attaches context hashes to critical calls. Detects suspicious mid-session pattern changes like VPN jumps or emulator switches.', icon: 'ShieldCheck', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'obfuscation-hardening', index: 27, name: 'Obfuscation & Code-Hardening Layer', shortName: 'Obfuscate', category: 'binary', description: 'String encryption, control-flow flattening, and name mangling for sensitive native and RN bridge modules. Pluggable for Android and iOS build chains with sensitivity tags.', icon: 'Lock', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'asset-protection', index: 28, name: 'Asset & Resource Protection Layer', shortName: 'Assets', category: 'storage', description: 'Selectively encrypts high-value assets (UI layouts, logic configs, anti-tamper version maps). Runtime streaming decryption with caching and asset integrity manifest.', icon: 'FileLock2', status: 'standby', riskLevel: 'low', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'js-bundle-shield', index: 29, name: 'JS Bundle Shield Layer', shortName: 'Bundle', category: 'integrity', description: 'Wraps the React Native JS bundle with content hash verification on startup, optional signed bundle requirement, and differential integrity checks after OTA updates.', icon: 'ShieldHalf', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'runtime-sensing', index: 30, name: 'Runtime Environment Sensing Layer', shortName: 'Sensing', category: 'environment', description: 'Detects root/jailbreak signals, emulator patterns, debugger traces, and hook frameworks. Maintains a Stealth Environment Score and routes data to risk layers.', icon: 'Eye', status: 'active', riskLevel: 'low', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'anti-tamper-hook', index: 31, name: 'Anti-Tamper & Hook Detection Layer', shortName: 'AntiHook', category: 'integrity', description: 'Monitors loaded libraries and known hook points. Detects unexpected shared libs, modified function prologues, and abnormal call stacks with updateable signature sets.', icon: 'ShieldCheck', status: 'active', riskLevel: 'low', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'network-transport-guard', index: 32, name: 'Network & Transport Guard Layer', shortName: 'Transport', category: 'network', description: 'Enforces TLS with pinning policy, minimal accepted protocol versions, encrypted payload envelopes, and replay detection tokens for key operations. HTTP client wrapper for RN.', icon: 'Network', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'match-integrity', index: 33, name: 'Match & Gameplay Integrity Layer', shortName: 'Match', category: 'integrity', description: 'Sits between client gameplay actions and server submissions. Tags actions with local monotonic ticks, device/session risk snapshots, and client-side plausibility checks.', icon: 'ShieldHalf', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'telemetry-evidence', index: 34, name: 'Telemetry & Evidence Layer', shortName: 'Telemetry', category: 'observability', description: 'Privacy-aware telemetry schema for environment scores, integrity results, update chain events, and gameplay anomaly scores. Batches with exponential backoff and offline encrypted caching.', icon: 'Activity', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'risk-scoring-policy', index: 35, name: 'Risk Scoring & Policy Decision Layer', shortName: 'RiskScore', category: 'prediction', description: 'Consumes telemetry, environment, and device scores to produce a unified Stealth Risk Score (0-100). Maps risk bands to actions: normal, watch, restrict, or lockdown.', icon: 'Gauge', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'ux-degradation', index: 36, name: 'UX-Safe Degradation Layer', shortName: 'UX', category: 'governance', description: 'Translates policy decisions into user-facing behavior: soft blocks (longer matchmaking), hard blocks (no ranked mode), and informative friction with localized messaging.', icon: 'Settings2', status: 'standby', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'secure-storage', index: 37, name: 'Secure Storage & Key Management Layer', shortName: 'Storage', category: 'storage', description: 'Encapsulates platform keystores and secure storage. Manages token storage, local config secrets, and asset decryption keys with rotation policies and per-environment keys.', icon: 'KeyRound', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'build-release-integrity', index: 38, name: 'Build & Release Integrity Layer', shortName: 'Build', category: 'build', description: 'Hooks into CI/CD to enforce signed build artifacts and assemble a Release Manifest with hashes, module versions, and signatures. SDK-side validator checks manifest on startup.', icon: 'Package', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'ota-governance', index: 39, name: 'OTA & Hot Update Governance Layer', shortName: 'OTA', category: 'update', description: 'Governs over-the-air JS and config updates. All updates must be signed and versioned. Maintains an update ledger per device and enforces server-side allowed update windows.', icon: 'RefreshCw', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'privacy-compliance', index: 40, name: 'Privacy & Compliance Guardrail Layer', shortName: 'Privacy', category: 'privacy', description: 'Implements constraints for PII and regional rules (EU/ES). Controls which signals can be collected, retention windows, and user consent states. Provides a compliance view for audits.', icon: 'Globe', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'observability-debug', index: 41, name: 'Observability & Debug Bridge Layer', shortName: 'Observe', category: 'observability', description: 'Allows safe, rate-limited introspection in dev and staging: toggle layers, see risk scores in real time, review environment detection logs. Production is read-only and policy-controlled.', icon: 'Stethoscope', status: 'standby', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'performance-monitor', index: 42, name: 'Performance & Degradation Monitor Layer', shortName: 'Perf', category: 'performance', description: 'Tracks CPU, memory, frame time, and network overhead per protection module. Auto-dials back intensity if budgets are exceeded on a device class. Feeds metrics into Risk Scoring Layer.', icon: 'Gauge', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'cross-platform-abstraction', index: 43, name: 'Cross-Platform Abstraction Layer', shortName: 'Platform', category: 'platform', description: 'Provides a unified TypeScript interface for RN and native: StealthWrapper.initialize, getRiskScore, reportEvent. Hides platform-specific implementations behind a common API.', icon: 'Smartphone', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'governance-killswitch', index: 44, name: 'Governance & Kill-Switch Layer', shortName: 'KillSwitch', category: 'governance', description: 'Central control for emergencies: disable misbehaving rule sets, roll back bad signatures, force security posture changes for critical incidents. Logs all governance actions for auditability.', icon: 'Power', status: 'standby', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'update-trust-chain', index: 45, name: 'Update Trust Chain', shortName: 'TrustChain', category: 'update', description: 'Every build and OTA update has a unique version ID, content hash, signer identity, and timestamp. Client validates the entire chain from installed version back to a known-trusted root.', icon: 'FileCheck2', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'update-policy-engine', index: 46, name: 'Update Policy Engine', shortName: 'UpdPolicy', category: 'update', description: 'Rules that decide if an update can be applied: min/max version constraints, environment constraints (WiFi only, low-risk devices), cohort rollout percentages, and guarded feature flags.', icon: 'Settings2', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'safe-staging-canary', index: 47, name: 'Safe-Staging & Canary Flows', shortName: 'Canary', category: 'update', description: 'Pushes updates to internal QA devices and small public canary cohorts. Collects compatibility and crash data before global rollout with automatic rollback if thresholds are exceeded.', icon: 'Download', status: 'standby', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'differential-integrity', index: 48, name: 'Differential Integrity Checks', shortName: 'DiffCheck', category: 'update', description: 'For JS bundle updates: compares new bundle hash with manifest, checks known sensitive module regions. High-risk deltas trigger heightened review, blocking, sandboxing, or feature degradation.', icon: 'FileCheck2', status: 'active', riskLevel: 'low', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'rollback-recovery', index: 49, name: 'Rollback & Recovery System', shortName: 'Rollback', category: 'update', description: 'Local rollback slots keep last known-good bundle and config. If startup checks fail after update, auto-rollback and tag the update as suspect. Server can flag versions as unsafe for network-coordinated rollback.', icon: 'Rewind', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'signature-ruleset-updates', index: 50, name: 'Signature & Rule-Set Updates', shortName: 'SigUpdate', category: 'update', description: 'Updates to anti-tamper signatures, environment heuristics, and risk scoring weights. All rule-set updates are signed, versioned, and subject to the same policy engine as app updates.', icon: 'ShieldCheck', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'update-ux', index: 51, name: 'User-Facing Update Experience', shortName: 'UpdUX', category: 'update', description: 'UX principles for updates: clear messaging when required for integrity, graceful deferral windows, non-punitive language unless hard enforcement is needed for competitive modes.', icon: 'Settings2', status: 'standby', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
  { id: 'update-telemetry-audit', index: 52, name: 'Update Telemetry & Audit', shortName: 'Audit', category: 'observability', description: 'Logs every update attempt, success, failure, and rollback with policy decisions. Exposes summarized views for security teams (risk, anomalies) and product teams (adoption, failures).', icon: 'Eye', status: 'active', riskLevel: 'none', isSimulated: true, isAbstract: false, isEducational: true },
];

export const featureMap: Record<string, Feature> = Object.fromEntries(
  features.map((f) => [f.id, f]),
);

export function getFeatureById(id: string): Feature | undefined {
  return featureMap[id];
}

export function getFeaturesByCategory(category: string): Feature[] {
  return features.filter((f) => f.category === category);
}
